const C = {
MEDIA:['sticker','stickervid','toimage','tovideo','toaudio','tovoice','tourl','togif','todoc <filename>','toview','toviewonce','vv','vv2','take <packname>','mediatag','removebg','imgtext','ocr','wm','sub','subtitle','mtovideo','couplepp','steal','del','delete','forward <jid>','volaudio <vol>','volvideo <vol>'],
'STICKER TOOLS':['stickerinfo','txtsticker','tgsticker <t.me/addstickers/link>','album'],
OWNER:['owner','ping','runtime','profile','support','feedback','alive','setalive <text>','setsudo @user','delsudo @user','listsudo','block <num>','unblock <num>','listblocked','setpp (reply image)','delpp','setppname <text>','setbio <text>','getpp','getname','pinchat','unpinchat','join <link>','joinch <link>','leave','broadcast <text>','broadcast2 <234> <text>','save (reply media)','sendgclink <num>','reactch <link> <emoji>','idch','checkidch','autotyping','autorecording','autoread','autoviewstatus on/off','alwaysonline','autoreact','anticall on/off','listgc','totalcmd','totalmembers','membercount','mblock','mbsearch'],
SETTINGS:['setprefix <sym>','public','private','setname <name>','setowner <num>','setmenuimage <url>','setwelcome on/off/reset','setgoodbye on/off/reset','modstatus','modsettings'],
STATUS:['togcstatus','totgstatus2 / poststatus','mstatus /groupstatus'],
GROUP:['kick @user','add <num>','promote @user','demote @user','promoteall','demoteall','demotealladmins','kickall','findfriends','ban @user','unban @user','listban','warn @user','unwarn @user','listwarn','resetwarns @user','autolink (any url)','tagall','hidetag <text>','tagadmins','announce <text>','open','close','opentime','closetime','setgcname <name>','setgcdesc <text>','setgcpp (reply image)','delgcpp','getlink','revoke','acceptall','rejectall','gcinfo','groupid','listmembers','admins','pin','unpin','poll <q>|<o1>|<o2>','creategc <name>','left','find','listactive'],
'GROUP MANAGEMENT':['mute-gc <dur>','unmute-gc','announcement <text>','report @user','event Title | DD/MM/YYYY | HH:MM','eventinfo (reply)','online @user','contact <num> [name]'],
PROTECTION:['antilink on/off/warn/kick/reset','antifwd on/off/warn/kick','antibot on/off/warn/kick','antigroupmention on/off/warn/kick','antispam on/off/warn/kick','antitag on/off/warn/kick','antibadword on/off','antibadwords add <word>','antipromote on/off','antidemote on/off','flood on/off','antidelete on/off/warn/kick','antigroupstatus on/off/warn/kick'],
INTERACTIVE:['button <q> | <b1> | <b2>','list <title> <desc> <opt...>','edit <text> (reply bot)','keep (reply)','fwdviewonce <jid>','reactto <emoji> (reply)','pollresults (reply)'],
'IMAGE PROCESSING':['mich-meme top | bottom (reply)','quoteimg <text> | <author>','crop <wxh> (reply)','resize <50%> or <200x200>','filter greyscale|sepia|blur','wanted (reply image)','wasted (reply image)','jail (reply image)','invert (reply image)','rainbow (reply image)','hd / enhance (reply image)','carbon <code>','brat <text>'],
UTILITY:['say <text>','translate <lang> <text>','tr <lang> <text>','style <text>','fancy <text>','readmore <text>','calc <expr>','calculator <expr>','morse <text>','morsecode <text>','ssweb <url>','screenshot <url>','imgur (reply)','get <url>','checkweb <url>','urlinfo <url>','linkinfo <url>','passcheck <pwd>','passwordcheck <pwd>','getdevice','archive','unarchive','setcmd','delcmd','listcmd','tts <text>','speak <text>','whois @user','app','dl <url>','flip','reset','top','scores','pay @user <amt>','bet <amt>','rch <link>','img <q>','describe <url>','qrcode <text>','readqr (reply image)','shorturl <url>','pdftotext (reply pdf)','advice','colorinfo <hex>','genderpredict <name>','zipcode <zip> <country>','aidetect <text>','forecast <city>'],
SEARCH:['google <q>','gsearch <q>','wiki <q>','wikipedia <q>','npmsearch <pkg>','npmstalk <pkg>','pinterest <q>','pixabay <q>','gimage <q>','dictionary <word>','define <word>','moviesearch <title>','movieinfo <title>','imdb <title>','moviedb <title>','recipe <dish>','weather <city>','wth <city>','wx <city>','ipinfo <ip>','track-ip <ip>','myip','bible <ref>','quran <ref>','element <name>','shazam','horoscope <sign>','tiktokstalk <user>','igstalk <user>','ytstalk <user>','fbstalk <user>','twstalk <user>','wastalk <num>','inspiration','nasaphoto','apod','news <topic>','randomfact','rfact','mfact','numberfact <n>','asteroid','waifu','ero','artwork <query>','musicinfo <artist>','michsearch <title>','wallpaper <query>','xnxx'],
'FUN & SOCIAL':['truth','dare','wyr','wouldyou','ship @u1 @u2','riddle','pickupline','rizz','insult','simi <msg>','catfact','catpic','dogpic','emojimix 😎+🥰','emix 😎+🥰','meme','joke','jokeplus <category>','dadjoke','chucknorris <category>','breakingbad','fact','quote','numbergame','nsfwgen <prompt>','text2nsfw <prompt>','8ball','fortune','tarot','battle @user'],
ECONOMY:['economy on/off','bal','balance','wallet','daily','work','deposit <amt>','withdraw <amt>','give @user <amt>','rob @user','gamble <amt>','lb','leaderboard','shop','buy <item>','inv','inventory','steal','crime','hunt','fish','mine','level','ecoinfo','bail'],
'ANIME & GIF':['animenews','animewlp','animewallpaper','animechar <name>','animerec <title>','animesearch <title>','animequote <name>','digimon <name>','hug','kiss','kill','slap','pat','lick','bite','yeet','bully','bonk','wink','poke','nom','smile','wave','blush','dance','cry','happy','laugh','angry','cuddle','highfive','shoot','sleep','awoo','smug','glomp','cringe','handhold','shinobu','fox','koala','bird','panda','dog','cat'],
'EPHOTO EFFECTS':['ephotolist','ephotostyles','glitchtext <text>','cyberpunk <text>','neonmetal <text>','gaminglogo <text>','graffiti <text>','sandwriting <text>','galaxy <text>','rainbow <text>','matrix <text>','watercolor <text>','neonlight <text>','glitch2 <text>','chalkboard <text>','3dstone <text>','3dgold <text>','goldflag <text>','smoke <text>','ice <text>','underwater <text>','vaporwave <text>','color <hex>','currency <amt> <from> <to>'],
AI:['ask <q>','ai <q>','gpt <q>','codeai <desc>','codegen <desc>','imagine <prompt>','imagine-ai <prompt>','imagine2 <prompt>','sdimage <prompt>','aiimage <prompt>','aiimage2 <prompt>','aigenimage <prompt>','flux <prompt>','fluxxmd <prompt>','pollinations <prompt>','genimage <prompt>','nanobananapro <prompt>','gen <prompt>','generate <prompt>','gemini-vision <url>','chatbot on/off','chatbot private on/off','chatbot clear'],
'AUDIO EFFECTS':['bass','blown','deep','robot','tiny','chipmunk','slowed','reverb','nightcore','earrape','echo','underwater','telephone','reverse','vaporwave'],
DOWNLOAD:['play <song>','song <name>','sing <name>','music <name>','sonu <prompt>','scdlsearch <song>','gitclone <url>','pinterestdl <url>','ytmp3 <link>','ytmp4 <link>','ytaudio <link>','ytvideo <link>','ytsearch <q>','tiktok <link>','tt <link>','tiktokmp3 <link>','tiktokimg <link>','ttsearch <q>','ig <link>','igdl <link>','fbdl <link>','scdl <link>','soundcloud <link>','tw <link>','dlall <url>','downloadall <url>','apk <app>','apkdl <app>','apkdownload <app>','mediafire <link>','mfdl <link>','pintdl <link>','gdrive <link>','spotifysearch <song>','spsearch <song>','spotifydl <id>','lyrics <song>','lyric <song>','lyric2 <song>','film <title>','movie <title>','movie2 <title>','movie2detail <url>','moviebox <title>','moviedetail <url>','movie-dl <url>','cinesubz <title>','video <q>','moviedl <title>','seriesdl <title> <s> <ep>','michsearch <title>','trending'],
SPORTS:['livescore','scores','fixtures <league>','schedule <league>','sportnews <topic>','standings <league>','table <league>','team <name>','player <name>','league <name>','h2h <team1> vs <team2>','sporttrivia','sportanswer <answer>','transfers','transfernews','sportstats <team>','f1','nhl'],
'FUN FACTS & INFO':['cocktail <name>','makeup <brand>','disney <character>','remotejobs <skill>','chucknorris <category>','asteroid','artwork <query>','nasaphoto'],
GAMES:['games','gamelist','tictactoe @user','ttt @user','tttmove <1-9>','numguess','numbergame','guess <num>','rps rock/paper/scissors','trivia','answer a/b/c/d','scramble','unscramble <word>','hangman','hmguess <letter>','mathquiz','mathans <num>','dice','coinflip','wouldyou','wyr','wordchain','wcg','emojiquiz','eqanswer <guess>','sporttrivia','sportanswer <answer>','endgame','tetris','2048','flappy','xo','simon','snake','breakout','pong','whack','invaders','memory','minesweeper','hangmangame','connect4','reaction','bubblepop','wordle','wordsearch','rpsgame','checkers','stacktower','sudoku','fruitslicer','archery','airhockey','chess','ludo']
};
export function renderMenu(s) {
  const runtime = formatRuntime(process.uptime());
  const head = `╭✰ ${s.botName}\n┃ 📱 Version: ${s.version}\n┃ 👑 Owner: +${s.owner}\n┃ 👤 User: ${s.botUser}\n┃ 🤖 Bot: ${s.botNumber}\n┃ ⏰ Runtime: ${runtime}\n┃ 🔧 Mode: ${String(s.mode).toUpperCase()}\n┃ 📝 Prefix: ${s.prefix}\n┃ 👥 Status: Private Chat\n┃ 🖥️ Host: Pterodactyl\n┃ 💻 Platform: linux\n╰✰\n\n▶ᴛʏᴘᴇ ${s.prefix}menu2 ғᴏʀ sʜᴏʀᴛᴇʀ ᴍᴇɴᴜ ʟɪsᴛ\n\n【 𝐂𝐎𝐌𝐌𝐀𝐍𝐃𝐒 】`;
  const sections = Object.entries(C).map(([name, cmds]) => `\n╭✰ ⟬ 𝐀${name.startsWith('I')?'': ''}${name} ⟭\n${cmds.map(x=>`│ ${s.prefix}${x}`).join('\n')}\n╰✰`).join('\n');
  return head + sections + '\n\n> © Powered by KING';
}
export function renderShortMenu(s){return `╭✰ ${s.botName}\n┃ Version: ${s.version}\n┃ Owner: +${s.owner}\n┃ Prefix: ${s.prefix}\n╰✰\n\n${Object.keys(C).map(k=>`• ${s.prefix}${k.toLowerCase().replaceAll(' ','_')}`).join('\n')}\n\n> © Powered by suprise`;}
function formatRuntime(sec){const d=Math.floor(sec/86400);sec%=86400;const h=Math.floor(sec/3600);sec%=3600;const m=Math.floor(sec/60);const s=Math.floor(sec%60);return `${d?d+'d ':''}${h?String(h).padStart(2,'0')+'h ':''}${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`;}
export const ALL_COMMANDS = Object.values(C).flat().map(x=>x.split(/\s|</)[0]).filter(Boolean);
